name: ci-build-node-workflow
on: 
  pull_request:
    branches:
      - develop

jobs:
  run-ci:
    runs-on: ubuntu-latest
    container: node:16
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: node --version
      - run: npm --version
      - run: npm install
      - run: npm run test
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
